[pytest]
testpaths = tests
python_files = test_*.py
addopts = -q -p no:cacheprovider -W ignore::DeprecationWarning -W ignore::sqlalchemy.exc.LegacyAPIWarning
markers =
    models: pruebas de los modelos de SQLAlchemy
